version: "3.7"

services:
  http:
    image: nginx:alpine
    expose:
      - 80
    networks:
      - default
    volumes:
      - ./src:/var/www
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    environment:
      VIRTUAL_HOST: recipe.localhost

  php:
    build:
      dockerfile: php.dockerfile
      context: .
    depends_on:
      - db
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www
      - /var/www/vendor
    restart: always
    environment:
      DATABASE_PATH: postgres://recipe@db/recipe

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: recipe
      POSTGRES_USER: recipe
      POSTGRES_PASS: recipe

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      sh -c 'redis-server /usr/local/etc/redis/redis.conf'

volumes:
  db-data:

networks:
  default:
    external: true
    name: nginx-proxy
